### ISSUE TITLE
How to compile it ?

### ISSUE THREAD

**Issue by gfelot** [LeFlou/qnetsoul#1]
Hi,
Thanks for this new version with QT5.
In the 1.5 version we already had a binary to use it.
I don't see it anymore or a Makefile to compile, so, how do we use this 1.6 ?

**Comment by gfelot** [comment]
Hi,

I figured it out how to do it with QMake (via install of QtCreator).

Generated a Makefile but having compile error here

`src/main.cpp:18:21: fatal error: QtWidgets: No such file or directory
 #include <QtWidgets>
                     ^
compilation terminated.
Makefile:502: recipe for target 'obj/main.o' failed
make[1]: *** [obj/main.o] Error 1
make[1]: Leaving directory '/home/ragnar/Epitech/qnetsoul-master/qns'
Makefile:41: recipe for target 'sub-qns-make_default' failed
make: *** [sub-qns-make_default] Error 2`

**Comment by RichardDally** [comment]
Are you using Qt5 or Qt4 ?
